apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app1-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 247069422203.dkr.ecr.us-east-2.amazonaws.com/argocd-demo-backend-ecr:v1.0.1
          ports:
            - containerPort: 5000